require('plugins.plugin-configs.impatient');
require('plugins.plugin-configs.lualine');
require('plugins.plugin-configs.nvimtree');
require('plugins.plugin-configs.commentnvim');
require('plugins.plugin-configs.telescope');
require('plugins.plugin-configs.toggleterm');
require('plugins.plugin-configs.auto-pairs');
require('plugins.plugin-configs.gitsigns');
require('plugins.plugin-configs.cmp');
require('plugins.plugin-configs.treesitter');
require('plugins.plugin-configs.mason');
require('plugins.plugin-configs.null-ls');
require('plugins.plugin-configs.prettier');
require('plugins.plugin-configs.indent-blankline');
require('plugins.plugin-configs.alpha');
require('plugins.plugin-configs.leapnvim');
require('plugins.plugin-configs.rose-pine')
require('plugins.plugin-configs.bufferline')
require('plugins.plugin-configs.git-conflicts')
-- require('plugins.plugin-configs.gruvbox')
